// The worklet bundle is generated by `wdk-worklet-bundler generate` into
// .wdk-bundle/. Metro treats it as a static asset; type it as a string.
declare module '*/wdk-worklet.bundle.js' {
  const bundle: string;
  export default bundle;
}
