// withModularHeaders.js
//
// Expo Config Plugin — injects `use_modular_headers!` into the generated
// Podfile so that `expo prebuild && pod install` completes on a clean clone.
//
// Without this, two categories of pods fail to build:
//   - AppCheckCore (pulled by @react-native-google-signin → GoogleSignIn ~>9
//     → Firebase) — requires module maps not generated by default.
//   - SwiftNIO / gRPC-Swift pods (pulled by the Spark wallet) — same issue.
//
// Note: "useFrameworks": "static" in expo-build-properties is NOT a viable
// alternative — it breaks the app at runtime. This plugin adds
// `use_modular_headers!` globally, which fixes both pod categories without
// the static-frameworks breakage.

const { withDangerousMod, createRunOncePlugin } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const withModularHeaders = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (modConfig) => {
      const podfilePath = path.join(
        modConfig.modRequest.platformProjectRoot,
        'Podfile'
      );

      if (!fs.existsSync(podfilePath)) {
        console.warn('[withModularHeaders] Podfile not found — skipping');
        return modConfig;
      }

      let contents = fs.readFileSync(podfilePath, 'utf8');

      if (!contents.includes('use_modular_headers!')) {
        contents = contents.replace(
          /^(platform :ios,.+)$/m,
          '$1\nuse_modular_headers!'
        );
        fs.writeFileSync(podfilePath, contents, 'utf8');
        console.log('[withModularHeaders] Podfile patched: added use_modular_headers!');
      } else {
        console.log('[withModularHeaders] Podfile already has use_modular_headers!');
      }

      return modConfig;
    },
  ]);
};

module.exports = createRunOncePlugin(withModularHeaders, 'withModularHeaders', '1.0.0');
